movement_controller_node:
  ros__parameters:
    A_h: 0.5236  # 30 degrees
    A_v: 1.0  # 57.3 degrees
    O_h: 0.0  # 0 degrees
    O_v: 0.0  # 0 degrees
    T: 5.0
    a_max: 1.0472
    a_min: 0.08727
    alpha_distribution:
    - 2.5
    - 1.5
    - 0.5
    - -0.5
    - -1.5
    - -2.5
    delta: 0.0
    delta_max: 0.1745
    delta_offset: 0.0
    delta_phi_h: 2.0944  # 120 degrees
    delta_phi_v: 3.5904  # 205.7 degrees
    delta_phi_vh:
      varies: true
      values:
      - -3.1416  # -180 degrees
      - -3.0543  # -175 degrees
      - -2.9671  # -170 degrees
      - -2.8798  # -165 degrees
      - -2.7925  # -160 degrees
      - -2.7053  # -155 degrees
      - -2.618  # -150 degrees
      - -2.5307  # -145 degrees
      - -2.4435  # -140 degrees
      - -2.3562  # -135 degrees
      - -2.2689  # -130 degrees
      - -2.1817  # -125 degrees
      - -2.0944  # -120 degrees
      - -2.0071  # -115 degrees
      - -1.9199  # -110 degrees
      - -1.8326  # -105 degrees
      - -1.7453  # -100 degrees
      - -1.6581  # -95 degrees
      - -1.5708  # -90 degrees
      - -1.4835  # -85 degrees
      - -1.3963  # -80 degrees
      - -1.309  # -75 degrees
      - -1.2217  # -70 degrees
      - -1.1345  # -65 degrees
      - -1.0472  # -60 degrees
      - -0.9599  # -55 degrees
      - -0.8727  # -50 degrees
      - -0.7854  # -45 degrees
      - -0.6981  # -40 degrees
      - -0.6109  # -35 degrees
      - -0.5236  # -30 degrees
      - -0.4363  # -25 degrees
      - -0.3491  # -20 degrees
      - -0.2618  # -15 degrees
      - -0.1745  # -10 degrees
      - -0.0873  # -5 degrees
      - 0.0  # 0 degrees
      - 0.0873  # 5 degrees
      - 0.1745  # 10 degrees
      - 0.2618  # 15 degrees
      - 0.3491  # 20 degrees
      - 0.4363  # 25 degrees
      - 0.5236  # 30 degrees
      - 0.6109  # 35 degrees
      - 0.6981  # 40 degrees
      - 0.7854  # 45 degrees
      - 0.8727  # 50 degrees
      - 0.9599  # 55 degrees
      - 1.0472  # 60 degrees
      - 1.1345  # 65 degrees
      - 1.2217  # 70 degrees
      - 1.309  # 75 degrees
      - 1.3963  # 80 degrees
      - 1.4835  # 85 degrees
      - 1.5708  # 90 degrees
      - 1.6581  # 95 degrees
      - 1.7453  # 100 degrees
      - 1.8326  # 105 degrees
      - 1.9199  # 110 degrees
      - 2.0071  # 115 degrees
      - 2.0944  # 120 degrees
      - 2.1817  # 125 degrees
      - 2.2689  # 130 degrees
      - 2.3562  # 135 degrees
      - 2.4435  # 140 degrees
      - 2.5307  # 145 degrees
      - 2.618  # 150 degrees
      - 2.7053  # 155 degrees
      - 2.7925  # 160 degrees
      - 2.8798  # 165 degrees
      - 2.9671  # 170 degrees
      - 3.0543  # 175 degrees
      - 3.1416  # 180 degrees
    publish_rate: 50.0
    sliding_pad_joint_count: 7
    swivel_joint_count: 6
